[relaychain]
default_command = "polkadot"
chain_spec_path = "./test/specs/paseo-local.json"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 1000
chain_spec_path = "./test/specs/asset-hub-paseo-local.json"

[parachains.collator]
name = "dave"
ws_port = 9988
command = "polkadot-omni-node"
args = [ "-lparachain=error,xcm=trace" ]

[[parachains]]
id = 4518
chain_spec_path = "./artifacts/latest_plain_chain_spec.json"

[parachains.collator]
name = "charlie"
ws_port = 9988
command = "polkadot-omni-node"
args = [ "-lparachain=error,xcm=trace"]