[relaychain]
default_command = "polkadot"
chain = "rococo-local"
chain_spec_path = "./rococo.json"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 1000
chain_spec_path = "./dev_spec.json"

[parachains.collator]
name = "alice"
ws_port = 9988
command = "./target/release/educhain-node"
